name: aprovacao
description: "Uma alternativa aos métodos atuais de estudo para provas de certificação"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3 
  get_it: ^7.1.3
  dartz: ^0.10.0-nullsafety.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "logo_icon"
  ios: true
  image_path: "assets/icon-aprovacao.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: MyriadProBold
      fonts:
        - asset: fonts/MYRIADPRO-BOLD.OTF
    - family: MyriadProRegular
      fonts:
        - asset: fonts/MYRIADPRO-REGULAR.OTF
    - family: MyriadProSemiBold
      fonts:
        - asset: fonts/MYRIADPRO-SEMIBOLD.OTF