name: professional_development
description: "Um aplicativo sobre os biomas com arquitetura limpa, ou quase."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3 
  get_it: ^7.1.3
  dartz: ^0.10.0-nullsafety.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.0.6
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.9
  value_listenable_test: any
  
flutter_launcher_icons:
  android: "logo_icon"
  ios: true
  image_path: "assets/biome-logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
